### ISSUE TITLE
Sweet Revolution

### ISSUE THREAD

**Issue by Dulciphi** [cosmicdan/RevolutionDulciphi#1]
cause nothing's sweeter than revolting xD

**Comment by cosmicdan** [comment]
You want me to rename the repo?

**Comment by Dulciphi** [comment]
hmm.. I do like the sound of "Sweet Revolution". It does sound a lot better than sticking my tag on it, too, especially since you're doing most of the work. :P 
...or "Revolution Le Dan Dan".
