### ISSUE TITLE
BOP update. Disabled Biomes no longer registered to Biome Dictionary

### ISSUE THREAD

**Issue by Dulciphi** [cosmicdan/RevolutionDulciphi#3]
Reference [BOP issue #567] (https://github.com/Glitchfiend/BiomesOPlenty/issues/567#issuecomment-165059191)

This will enable introduction of Highlands to the pack without exceeding Biome ID limit.

Eric set up a server (on the old Dedicated server) with Realistic Terrain Generation for us to take a look, but unfortunately didn't upload the mods or mod list that would enable us to.. It seems that entire dedicated server has since undergone a complete reinstall, updated to Debian 8. TeamSpeak is down. Do you know anything about this?

**Comment by cosmicdan** [comment]
Read Reika's latest comment on that issue thread.

He could have made a server in the new MineOS one, it can handle it fine. Old server is a P.O.S., isn't it?

Nope, I've not heard about this. I can try/see about installing TS on the new server though, if you want - seeing as how the old one will be gone soon. Or we can let Eric do it?

Anyway, I've added you as a collaborator to this repo - you should be able to clone and also push updates now. So I'll let you add/update mods at your own discretion too. But remember to do a "git pull" before you make any commits and/or pushes, to ensure you have the latest HEAD.

**Comment by Dulciphi** [comment]
Hmm.. well, I'm happy with the current biomes (minus the Tainted biome. That must go). So if you're happy without Highlands, it's safe to ignore.
Still lots to do. I've spoken to Eric since (Apologies for the rant). The old server has (at least) a month to run from today and it too is a [beast](http://www.soyoustart.com/us/offers/e3-sat-3.xml), capable of running many simultaneous packs in addition to ours. It is a large shame to see it unused.

Off Topic but not deserving of another issue: Do you mind if I change repo name? I'm thoroughly convinced by now of Rotarycraft/Electricraft over Thermal Expansion/MFR. That was the major reason for including Revolution as it was the major difference between it and my pack.
